/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/Chirag.glb 
*/

import React, { useEffect, useRef, useState, useMemo } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAnimations, useFBX, useGLTF, useScroll } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useControls } from "leva";
import * as THREE from "three";

// Preload only the main character model
useGLTF.preload("/models/Chirag.glb");

// Animation configuration object for efficient loading
const ANIMATIONS_CONFIG = [
  { path: "/animations/Waving.fbx", name: "Wave" },
  { path: "/animations/Talking Phone Pacing.fbx", name: "Talking" },
  { path: "/animations/Getting Up.fbx", name: "Up" },
  { path: "/animations/Jumping Down.fbx", name: "Down" },
  { path: "/animations/Male Sitting Pose.fbx", name: "Sitting" },
  { path: "/animations/Push Up.fbx", name: "PushUp" },
  { path: "/animations/Shooting Arrow.fbx", name: "Shoot" },
  { path: "/animations/Swing To Land.fbx", name: "Swing" },
];

export function Chirag(props) {
  const [hasPlayed, setHasPlayed] = useState(false);
  const { animation, scrollRef, isStart } = props;
  const { x, y, z, start, headflow, cursorflow, wireframe } = useControls({
    x: {
      value: 0,
      min: 0,
      max: 20,
      hidden: true,
    },
    y: {
      value: 0,
      min: 0,
      max: 20,
      hidden: true,
    },
    z: {
      value: 0,
      min: 0,
      max: 20,
      hidden: true,
    },
    start: {
      value: isStart,
      onChange: (value) => {
        setHasPlayed(value);
      },
      hidden: true,
    },
    wireframe: { value: false, hidden: true },
    headflow: { value: false, hidden: true },
    cursorflow: { value: false, hidden: true },
  });

  const groupRef = useRef();
  const { scene } = useGLTF("/models/Chirag.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  // Load all animations using useMemo to prevent reloading
  const animations = useMemo(() => {
    const loadedAnimations = ANIMATIONS_CONFIG.map((config) => {
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const { animations } = useFBX(config.path);
      animations[0].name = config.name;
      return animations[0];
    });
    return loadedAnimations;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const { actions } = useAnimations(animations, groupRef);

  useFrame((state) => {
    if (headflow && groupRef.current) {
      const head = groupRef.current.getObjectByName("Head");
      if (head) head.lookAt(state.camera.position);
    }
    if (cursorflow && groupRef.current) {
      const spine = groupRef.current.getObjectByName("Spine");
      if (spine) {
        const target = new THREE.Vector3(state.pointer.x, state.pointer.y, 1);
        spine.lookAt(target);
      }
    }
  });

  useEffect(() => {
    const currentAction = actions[animation];
    if (currentAction) {
      // Efficiently stop all other animations
      Object.values(actions).forEach((action) => {
        if (action !== currentAction) {
          action.fadeOut(0.5);
        }
      });
      // Play current animation
      currentAction.reset().fadeIn(0.5).play();
      // Set to play once if already played, otherwise loop
      currentAction.clampWhenFinished = true;
      if (hasPlayed) {
        currentAction.setLoop(THREE.LoopOnce);
      } else {
        currentAction.setLoop(THREE.LoopRepeat);
      }
      // setHasPlayed(true);
      return () => {
        currentAction.reset().fadeOut(0.5);
        setHasPlayed(isStart);
      };
    }
  }, [animation, actions, hasPlayed]);

  // useEffect(() => {
  //   Object.values(materials).forEach((material) => {
  //     material.wireframe = wireframe;
  //   });
  // }, [wireframe]);

  return (
    <group {...props} ref={groupRef} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}
